### PR TITLE
#33 Fix old version processing test

### PR DESCRIPTION
**Pull request by CAMOBAP**
- #33 

Open question:
 - `expressir@1.1.0` contains [breaking changes (`Schema` class moved under `Declaration` submodule)](https://github.com/lutaml/expressir/compare/v1.0.0...v1.1.0#diff-4e1467b4aa62e9075aee441f02beeb380efec08eb80167a5cf480ed59bbc2f8f). Should `expressir` correctly handle such cases to throw `Expressir::Error` instead `NameError: uninitialized constant Expressir::Model::Schema`

### CODE REVIEW

**Comment by CAMOBAP** [comment]
Ruby 3.1 failure is a known issue https://github.com/lutaml/expressir/issues/109

**Comment by ronaldtse** [comment]
@CAMOBAP can you help upgrade and see if we can merge? Feel free to merge. Thanks!

**Comment by CAMOBAP** [comment]
@ronaldtse re-triggered CI just in case, and will merge when passed

**Comment by ronaldtse** [comment]
@CAMOBAP Can you post the open question to the expressir repository? I believe @maxirmx can answer the question. Thanks!

**Pull request merged**
